version: '3.9'

# Network for Laravel
networks:
  web_network:
    name: laravel9
    driver: bridge

services:

  # PHP App Service 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-laravel9-app
    container_name: react_laravel9_app
    restart: always
    volumes:
      - ./src:/var/www
      - /var/www/vendor
      - /var/www/node_modules
    networks:
      - web_network

  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: react_laravel9_mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      # - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=laravel9db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
    ports:
      - "3307:3306"
    restart: always
    networks:
      - web_network

  # Nginx Web Server Service
  nginx:
    image: nginx:1.19.8-alpine
    container_name: react_laravel9_nginx
    volumes:
      - ./src:/var/www
      - ./nginx/conf:/etc/nginx/conf.d
    ports:
      - "8000:80"
    restart: always
    networks:
      - web_network

  # Redis (caching)
  redis:
    image: redis:6.2.1-buster
    container_name: react_laravel9_redis
    volumes: 
      - ./redis/data:/data
      # - /data
    ports:
      - "6379:6379"
    restart: always
    networks:
      - web_network      

  # MailHog (local mail testing)
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: react_laravel9_mailhog
    ports:
      - 8025:8025
    restart: always
    networks:
      - web_network

  # phpMyAdmin (MySQL managment)
  phpmyadmin:
    image: phpmyadmin:5.1.0-apache
    depends_on:
      - db
    container_name: react_laravel9_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      # PMA_USER: admin
      # PMA_PASSWORD: 1234
      PMA_ARBITRARY: 1
    ports:
      - 8200:80
    restart: always
    networks:
      - web_network

  # React App Service
  reactapp:
    build: frontend/
    image: react-laravel9-react-app
    container_name: react_laravel9_react_app
    volumes:
      - ./frontend:/usr/app
      - /usr/app/node_modules
    ports:
      # - "3000:3000"
      #- "3000:80"
      - "3000:5173"
    environment:
      - USEPOLLING=true
    restart: always
    networks:
      - web_network
      
